---
- include_vars: "{{role_path}}/vars/main.yml"

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Install software
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ software_list }}"
