---
- include_vars: "{{ role_path }}/vars/main.yml"
- name: Copy jenkins.service file
  template:
    src: "{{ role_path }}/templates/jenkins.service.j2"
    dest: /etc/systemd/system/jenkins.service

- name: Create initialization scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Add initialization script to setup jenkins password
  template:
    src: "{{ role_path }}/templates/security.groovy.j2"
    dest: "{{ jenkins_home }}/init.groovy.d/security.groovy"

- name: Start jenkins service
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: jenkins.service

- name: Wait jenkins
  wait_for:
     port: 8080

- name: Wait while Jenkins is getting ready
  uri:
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    url: "http://127.0.0.1:8080"
    return_content: yes
  register: response
  until: response.content.find('Please wait while Jenkins is getting ready') == -1
  retries: 10
  delay: 5

- name: Delete security.groovy file
  file:
    path: "{{ jenkins_home }}/init.groovy.d/security.groovy"
    state: absent

- name: Install plugin
  jenkins_plugin:
    name: "{{ item }}"
    timeout: 1000
    params:
      url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
  with_items: "{{ jenkins_plugins }}"

- name: Start jenkins service
  systemd:
    state: restarted
    name: jenkins.service
